language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install numpy
  - pip install pytest
  - pip install -e .

# command to run tests
script:
  - cd paramtools && pytest tests/ -v