dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install -e .

# command to run tests
script:
  - cd paramtools && pytest tests/ -v